---
k3s_version: v1.17.5+k3s1
ansible_user: ubuntu
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k8smaster'][0]]['ansible_host'] | default(groups['k8smaster'][0]) }}"
extra_server_args: "--disable traefik --disable servicelb --default-local-storage-path /mnt/disk01"
