---
- name: Update /etc/hosts
  become: true
  blockinfile:
      path: /etc/hosts
      create: yes
      block: |
        k8smaster 192.168.68.142
        k8snode01 192.168.68.141
        k8snode02 192.168.68.129
        k8snode03 192.168.68.149
        k8snode04 192.168.68.150
