- hosts: nfs_clients
  remote_user: ubuntu
  sudo: yes

  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=installed update_cache=yes

    - name: Create mountable dir
      file: path=/mnt/disk01 state=directory mode=777 owner=root group=root

    - name: set mountpoints
      mount: name=/mnt/disk01 src={{hostvars[groups['nfs_server'][0]]['ansible_eth0']['ipv4']['address']}}:/mnt/disk01 fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted