---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: ubuntu
    - role: housekeeping


- hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: nfs/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node
    - role: k3s/node