---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: download
    - role: ubuntu
    - role: housekeeping


- hosts: k8smaster
  become: yes
  roles:
    - role: k3s/master
    - role: nfs/master

- hosts: k8snodes
  become: yes
  roles:
    - role: k3s/node
    - role: k3s/node